// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_coverfire = NULL;
lv_obj_t * ui_TextArea4 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_cvTimer = NULL;
lv_obj_t * ui_cvResult = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Button9 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        cf_start_clbk(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        cf_stop_clbk(e);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PROGRAMS, LV_SCR_LOAD_ANIM_FADE_ON, 64, 0, &ui_PROGRAMS_screen_init);
    }
}

// build funtions

void ui_coverfire_screen_init(void)
{
    ui_coverfire = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_coverfire, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_coverfire, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_coverfire, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_coverfire, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_coverfire, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea4 = lv_textarea_create(ui_coverfire);
    lv_obj_set_width(ui_TextArea4, 350);
    lv_obj_set_height(ui_TextArea4, 347);
    lv_obj_set_x(ui_TextArea4, -193);
    lv_obj_set_y(ui_TextArea4, -24);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea4,
                         "Dwa cele na start.\nTrafienie jednego z nich aktywuje oczekiwanie kolejnego. Trafienie drugiego zaczyna kolejny cykl. 5 cykli.\n\nKolor aktywnego celu: czerwony\nKolor oczekujacego celu:\nzolty\n\nCzas: 5 cykli\nWynik: Czas\n\n");
    lv_textarea_set_placeholder_text(ui_TextArea4, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextArea4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TextArea4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextArea4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea4, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TextArea4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TextArea4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TextArea4, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TextArea4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_coverfire);
    lv_obj_set_width(ui_Button3, 150);
    lv_obj_set_height(ui_Button3, 100);
    lv_obj_set_x(ui_Button3, 101);
    lv_obj_set_y(ui_Button3, -142);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x11B532), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button3, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "start");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_tactic40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cvTimer = lv_textarea_create(ui_coverfire);
    lv_obj_set_width(ui_cvTimer, 150);
    lv_obj_set_height(ui_cvTimer, 130);
    lv_obj_set_x(ui_cvTimer, 99);
    lv_obj_set_y(ui_cvTimer, 42);
    lv_obj_set_align(ui_cvTimer, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cvTimer, "TIMER & STOPER");
    lv_textarea_set_placeholder_text(ui_cvTimer, "Placeholder...");
    lv_obj_set_style_text_font(ui_cvTimer, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cvResult = lv_textarea_create(ui_coverfire);
    lv_obj_set_width(ui_cvResult, 150);
    lv_obj_set_height(ui_cvResult, 128);
    lv_obj_set_x(ui_cvResult, 288);
    lv_obj_set_y(ui_cvResult, 43);
    lv_obj_set_align(ui_cvResult, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cvResult, "TRAFIENIA");
    lv_textarea_set_placeholder_text(ui_cvResult, "Placeholder...");
    lv_obj_set_style_text_font(ui_cvResult, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_cvResult, &lv_font_montserrat_16, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Button8 = lv_btn_create(ui_coverfire);
    lv_obj_set_width(ui_Button8, 150);
    lv_obj_set_height(ui_Button8, 100);
    lv_obj_set_x(ui_Button8, 285);
    lv_obj_set_y(ui_Button8, -141);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xF90101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button8, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button8, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "stop");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_tactic40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_btn_create(ui_coverfire);
    lv_obj_set_width(ui_Button9, 110);
    lv_obj_set_height(ui_Button9, 60);
    lv_obj_set_align(ui_Button9, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button9, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button9, &ui_img_mk_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button9, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);

}

void ui_coverfire_screen_destroy(void)
{
    if(ui_coverfire) lv_obj_del(ui_coverfire);

    // NULL screen variables
    ui_coverfire = NULL;
    ui_TextArea4 = NULL;
    ui_Button3 = NULL;
    ui_Label3 = NULL;
    ui_cvTimer = NULL;
    ui_cvResult = NULL;
    ui_Button8 = NULL;
    ui_Label4 = NULL;
    ui_Button9 = NULL;

}
