// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_T;
lv_obj_t * ui_settings = NULL;
lv_obj_t * ui_TARGET_1 = NULL;
lv_obj_t * ui_TARGET_2 = NULL;
lv_obj_t * ui_TARGET_3 = NULL;
lv_obj_t * ui_Button6 = NULL;
// event funtions
void ui_event_settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_menu_screen_init);
    }
}

// build funtions

void ui_settings_screen_init(void)
{
    ui_settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_settings, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_settings, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TARGET_1 = lv_checkbox_create(ui_settings);
    lv_checkbox_set_text(ui_TARGET_1, "TARGET 1");
    lv_obj_set_width(ui_TARGET_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TARGET_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TARGET_1, -258);
    lv_obj_set_y(ui_TARGET_1, -5);
    lv_obj_set_align(ui_TARGET_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TARGET_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_TARGET_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TARGET_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TARGET_1, &ui_font_tactic40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TARGET_1, lv_color_hex(0x0067FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TARGET_1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TARGET_1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TARGET_1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TARGET_1, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TARGET_1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_TARGET_2 = lv_checkbox_create(ui_settings);
    lv_checkbox_set_text(ui_TARGET_2, "TARGET 2");
    lv_obj_set_width(ui_TARGET_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TARGET_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TARGET_2, 2);
    lv_obj_set_y(ui_TARGET_2, -6);
    lv_obj_set_align(ui_TARGET_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TARGET_2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_TARGET_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TARGET_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TARGET_2, &ui_font_tactic40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TARGET_2, lv_color_hex(0x0067FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TARGET_2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TARGET_2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TARGET_2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TARGET_2, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TARGET_2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_TARGET_3 = lv_checkbox_create(ui_settings);
    lv_checkbox_set_text(ui_TARGET_3, "TARGET 3");
    lv_obj_set_width(ui_TARGET_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TARGET_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TARGET_3, 263);
    lv_obj_set_y(ui_TARGET_3, -9);
    lv_obj_set_align(ui_TARGET_3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TARGET_3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_TARGET_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TARGET_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TARGET_3, &ui_font_tactic40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TARGET_3, lv_color_hex(0x0067FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TARGET_3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TARGET_3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TARGET_3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TARGET_3, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TARGET_3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_Button6, 110);
    lv_obj_set_height(ui_Button6, 60);
    lv_obj_set_align(ui_Button6, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button6, &ui_img_mk_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button6, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);
    uic_T = ui_TARGET_1;

}

void ui_settings_screen_destroy(void)
{
    if(ui_settings) lv_obj_del(ui_settings);

    // NULL screen variables
    ui_settings = NULL;
    uic_T = NULL;
    ui_TARGET_1 = NULL;
    ui_TARGET_2 = NULL;
    ui_TARGET_3 = NULL;
    ui_Button6 = NULL;

}
