// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: range_training_screen

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label = NULL;
lv_obj_t * ui_Button1 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_call_function(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Label, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Label, -191);
    lv_obj_set_y(ui_Label, -24);
    lv_obj_set_align(ui_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label, "Demo - test");
    lv_obj_set_style_text_font(ui_Label, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 42);
    lv_obj_set_y(ui_Button1, -19);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label = NULL;
    ui_Button1 = NULL;

}
