// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_start_screen.h"
#include "ui_menu.h"
#include "ui_heavyfire.h"
#include "ui_ranking.h"
#include "ui_settings.h"
#include "ui_PROGRAMS.h"
#include "ui_coverfire.h"
#include "ui_dynamic.h"
#include "ui_training.h"
#include "ui_hostage.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_start_screen2_png);    // assets/start_screen2.png
LV_IMG_DECLARE(ui_img_ranking_png);    // assets/ranking.png
LV_IMG_DECLARE(ui_img_widget_settings_png);    // assets/widget_settings.png
LV_IMG_DECLARE(ui_img_widget_programs_png);    // assets/widget_programs.png
LV_IMG_DECLARE(ui_img_mk_png);    // assets/MK.png
LV_IMG_DECLARE(ui_img_trainig_png);    // assets/trainig.png
LV_IMG_DECLARE(ui_img_cover_fire_png);    // assets/cover_fire.png
LV_IMG_DECLARE(ui_img_dynamic_png);    // assets/dynamic.png
LV_IMG_DECLARE(ui_img_hostage_png);    // assets/hostage.png
LV_IMG_DECLARE(ui_img_heavy_fire_png);    // assets/heavy_fire.png

// FONTS
LV_FONT_DECLARE(ui_font_tactic16);
LV_FONT_DECLARE(ui_font_tactic40);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
