// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DYNAMIC_H
#define UI_DYNAMIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dynamic
extern void ui_dynamic_screen_init(void);
extern void ui_dynamic_screen_destroy(void);
extern void ui_event_dynamic(lv_event_t * e);
extern lv_obj_t * ui_dynamic;
extern lv_obj_t * ui_TextArea7;
extern void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_dynamicTimer;
extern lv_obj_t * ui_dynamicResult;
extern void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label8;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

