// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOSTAGE_H
#define UI_HOSTAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_hostage
extern void ui_hostage_screen_init(void);
extern void ui_hostage_screen_destroy(void);
extern lv_obj_t * ui_hostage;
extern lv_obj_t * ui_TextArea13;
extern void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_hostageTimer;
extern lv_obj_t * ui_hostageResult;
extern void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label12;
extern void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

