// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MENU_H
#define UI_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_menu
extern void ui_menu_screen_init(void);
extern void ui_menu_screen_destroy(void);
extern lv_obj_t * ui_menu;
extern void ui_event_rankingbutton(lv_event_t * e);
extern lv_obj_t * ui_rankingbutton;
extern void ui_event_settingsbutton(lv_event_t * e);
extern lv_obj_t * ui_settingsbutton;
extern void ui_event_programsbutton(lv_event_t * e);
extern lv_obj_t * ui_programsbutton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

