// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PROGRAMS_H
#define UI_PROGRAMS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PROGRAMS
extern void ui_PROGRAMS_screen_init(void);
extern void ui_PROGRAMS_screen_destroy(void);
extern lv_obj_t * ui_PROGRAMS;
extern void ui_event_trainingbutton(lv_event_t * e);
extern lv_obj_t * ui_trainingbutton;
extern void ui_event_coverfirebutton(lv_event_t * e);
extern lv_obj_t * ui_coverfirebutton;
extern void ui_event_dynamicbutton(lv_event_t * e);
extern lv_obj_t * ui_dynamicbutton;
extern void ui_event_hostagebutton(lv_event_t * e);
extern lv_obj_t * ui_hostagebutton;
extern void ui_event_heavyfirebutton(lv_event_t * e);
extern lv_obj_t * ui_heavyfirebutton;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

