// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settings
extern void ui_settings_screen_init(void);
extern void ui_settings_screen_destroy(void);
extern void ui_event_settings(lv_event_t * e);
extern lv_obj_t * ui_settings;
extern lv_obj_t * ui_TARGET_1;
extern lv_obj_t * ui_TARGET_2;
extern lv_obj_t * ui_TARGET_3;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_T;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

