// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TRAINING_H
#define UI_TRAINING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_training
extern void ui_training_screen_init(void);
extern void ui_training_screen_destroy(void);
extern lv_obj_t * ui_training;
extern lv_obj_t * ui_TextArea10;
extern void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_trainingTimer;
extern lv_obj_t * ui_trainingResult;
extern void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label10;
extern void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

