// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_COVERFIRE_H
#define UI_COVERFIRE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_coverfire
extern void ui_coverfire_screen_init(void);
extern void ui_coverfire_screen_destroy(void);
extern lv_obj_t * ui_coverfire;
extern lv_obj_t * ui_TextArea4;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_cvTimer;
extern lv_obj_t * ui_cvResult;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label4;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

