// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: range_training_screen

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void button_call_function(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
