// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HEAVYFIRE_H
#define UI_HEAVYFIRE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_heavyfire
extern void ui_heavyfire_screen_init(void);
extern void ui_heavyfire_screen_destroy(void);
extern lv_obj_t * ui_heavyfire;
extern lv_obj_t * ui_TextArea1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_hvtimer;
extern lv_obj_t * ui_hvresult;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern void ui_event_Label2(lv_event_t * e);
extern lv_obj_t * ui_Label2;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

