// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_start_screen_screen_init();
    ui_menu_screen_init();
    ui_heavyfire_screen_init();
    ui_ranking_screen_init();
    ui_settings_screen_init();
    ui_PROGRAMS_screen_init();
    ui_coverfire_screen_init();
    ui_dynamic_screen_init();
    ui_training_screen_init();
    ui_hostage_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_start_screen);
}

void ui_destroy(void)
{
    ui_start_screen_screen_destroy();
    ui_menu_screen_destroy();
    ui_heavyfire_screen_destroy();
    ui_ranking_screen_destroy();
    ui_settings_screen_destroy();
    ui_PROGRAMS_screen_destroy();
    ui_coverfire_screen_destroy();
    ui_dynamic_screen_destroy();
    ui_training_screen_destroy();
    ui_hostage_screen_destroy();
}
