// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_dynamic = NULL;
lv_obj_t * ui_TextArea7 = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_dynamicTimer = NULL;
lv_obj_t * ui_dynamicResult = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Button12 = NULL;
// event funtions
void ui_event_dynamic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dynamic, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dynamic_screen_init);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        dynamic_start_clbk(e);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        dynamic_stop_clbk(e);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PROGRAMS, LV_SCR_LOAD_ANIM_FADE_ON, 64, 0, &ui_PROGRAMS_screen_init);
    }
}

// build funtions

void ui_dynamic_screen_init(void)
{
    ui_dynamic = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dynamic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dynamic, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dynamic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_dynamic, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_dynamic, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea7 = lv_textarea_create(ui_dynamic);
    lv_obj_set_width(ui_TextArea7, 350);
    lv_obj_set_height(ui_TextArea7, 347);
    lv_obj_set_x(ui_TextArea7, -193);
    lv_obj_set_y(ui_TextArea7, -24);
    lv_obj_set_align(ui_TextArea7, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea7,
                         "Zaczynamy od jednego aktywnego celu. \nTrafienie aktywuje kolejny cel.\n10 cykli.\n\nKolor aktywnego celu:\nczerwony\n\nCzas: 10 cykli.\nWynik: Czas");
    lv_textarea_set_placeholder_text(ui_TextArea7, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextArea7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TextArea7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextArea7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea7, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea7, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TextArea7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TextArea7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TextArea7, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TextArea7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_btn_create(ui_dynamic);
    lv_obj_set_width(ui_Button10, 150);
    lv_obj_set_height(ui_Button10, 100);
    lv_obj_set_x(ui_Button10, 101);
    lv_obj_set_y(ui_Button10, -142);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0x11B532), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button10, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button10, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "start");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_tactic40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dynamicTimer = lv_textarea_create(ui_dynamic);
    lv_obj_set_width(ui_dynamicTimer, 150);
    lv_obj_set_height(ui_dynamicTimer, 130);
    lv_obj_set_x(ui_dynamicTimer, 99);
    lv_obj_set_y(ui_dynamicTimer, 42);
    lv_obj_set_align(ui_dynamicTimer, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_dynamicTimer, "TIMER & STOPER");
    lv_textarea_set_placeholder_text(ui_dynamicTimer, "Placeholder...");
    lv_obj_set_style_text_font(ui_dynamicTimer, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dynamicResult = lv_textarea_create(ui_dynamic);
    lv_obj_set_width(ui_dynamicResult, 150);
    lv_obj_set_height(ui_dynamicResult, 128);
    lv_obj_set_x(ui_dynamicResult, 288);
    lv_obj_set_y(ui_dynamicResult, 43);
    lv_obj_set_align(ui_dynamicResult, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_dynamicResult, "TRAFIENIA");
    lv_textarea_set_placeholder_text(ui_dynamicResult, "Placeholder...");
    lv_obj_set_style_text_font(ui_dynamicResult, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_dynamicResult, &lv_font_montserrat_16, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_dynamic);
    lv_obj_set_width(ui_Button11, 150);
    lv_obj_set_height(ui_Button11, 100);
    lv_obj_set_x(ui_Button11, 285);
    lv_obj_set_y(ui_Button11, -141);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0xF90101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button11, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button11, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "stop");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_tactic40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_btn_create(ui_dynamic);
    lv_obj_set_width(ui_Button12, 110);
    lv_obj_set_height(ui_Button12, 60);
    lv_obj_set_align(ui_Button12, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button12, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button12, &ui_img_mk_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button12, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dynamic, ui_event_dynamic, LV_EVENT_ALL, NULL);

}

void ui_dynamic_screen_destroy(void)
{
    if(ui_dynamic) lv_obj_del(ui_dynamic);

    // NULL screen variables
    ui_dynamic = NULL;
    ui_TextArea7 = NULL;
    ui_Button10 = NULL;
    ui_Label7 = NULL;
    ui_dynamicTimer = NULL;
    ui_dynamicResult = NULL;
    ui_Button11 = NULL;
    ui_Label8 = NULL;
    ui_Button12 = NULL;

}
