// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void hv_start_clbk(lv_event_t * e)
{
	// Your code here
}

void hv_stop_clbk(lv_event_t * e)
{
	// Your code here
}

void hv_program_set(lv_event_t * e)
{
	hv_start();
}

void cf_start_clbk(lv_event_t * e)
{
	// Your code here
}

void cf_stop_clbk(lv_event_t * e)
{
	// Your code here
}

void dynamic_start_clbk(lv_event_t * e)
{
	// Your code here
}

void dynamic_stop_clbk(lv_event_t * e)
{
	// Your code here
}

void training_start_clbk(lv_event_t * e)
{
	// Your code here
}

void training_stop_clbk(lv_event_t * e)
{
	// Your code here
}

void hostage_start_clbk(lv_event_t * e)
{
	// Your code here
}

void hostage_stop_clbk(lv_event_t * e)
{
	// Your code here
}

void hv_stop_clb(lv_event_t * e)
{
	// Your code here
}
