// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: range_training_screen

#include "ui.h"

void button_call_function(lv_event_t * e)
{
	sendMessage();
}
