// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_hostage = NULL;
lv_obj_t * ui_TextArea13 = NULL;
lv_obj_t * ui_Button16 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_hostageTimer = NULL;
lv_obj_t * ui_hostageResult = NULL;
lv_obj_t * ui_Button17 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Button18 = NULL;
// event funtions
void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        hostage_start_clbk(e);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        hostage_stop_clbk(e);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PROGRAMS, LV_SCR_LOAD_ANIM_FADE_ON, 64, 0, &ui_PROGRAMS_screen_init);
    }
}

// build funtions

void ui_hostage_screen_init(void)
{
    ui_hostage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_hostage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_hostage, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hostage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_hostage, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_hostage, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea13 = lv_textarea_create(ui_hostage);
    lv_obj_set_width(ui_TextArea13, 350);
    lv_obj_set_height(ui_TextArea13, 347);
    lv_obj_set_x(ui_TextArea13, -193);
    lv_obj_set_y(ui_TextArea13, -23);
    lv_obj_set_align(ui_TextArea13, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea13,
                         "Zaczynamy od jednego aktywnego celu i dwoch zakladnikow. 3 sekundy na trafienie. Trafienie aktywuje kolejny cel oraz zakadnikow.\nTrafienie zakladnika = przegrana.\n\nKolor aktywnego celu:\nczerwony\nKolo zakladnika:\nniebieski\n\nCzas: 5 cykli.\nWynik: Ilosc trafien");
    lv_textarea_set_placeholder_text(ui_TextArea13, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextArea13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TextArea13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextArea13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea13, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea13, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TextArea13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TextArea13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TextArea13, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TextArea13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button16 = lv_btn_create(ui_hostage);
    lv_obj_set_width(ui_Button16, 150);
    lv_obj_set_height(ui_Button16, 100);
    lv_obj_set_x(ui_Button16, 101);
    lv_obj_set_y(ui_Button16, -142);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0x11B532), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button16, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button16, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Button16);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "start");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_tactic40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hostageTimer = lv_textarea_create(ui_hostage);
    lv_obj_set_width(ui_hostageTimer, 150);
    lv_obj_set_height(ui_hostageTimer, 130);
    lv_obj_set_x(ui_hostageTimer, 99);
    lv_obj_set_y(ui_hostageTimer, 42);
    lv_obj_set_align(ui_hostageTimer, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_hostageTimer, "TIMER & STOPER");
    lv_textarea_set_placeholder_text(ui_hostageTimer, "Placeholder...");
    lv_obj_set_style_text_font(ui_hostageTimer, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hostageResult = lv_textarea_create(ui_hostage);
    lv_obj_set_width(ui_hostageResult, 150);
    lv_obj_set_height(ui_hostageResult, 128);
    lv_obj_set_x(ui_hostageResult, 288);
    lv_obj_set_y(ui_hostageResult, 43);
    lv_obj_set_align(ui_hostageResult, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_hostageResult, "TRAFIENIA");
    lv_textarea_set_placeholder_text(ui_hostageResult, "Placeholder...");
    lv_obj_set_style_text_font(ui_hostageResult, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_hostageResult, &lv_font_montserrat_16, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Button17 = lv_btn_create(ui_hostage);
    lv_obj_set_width(ui_Button17, 150);
    lv_obj_set_height(ui_Button17, 100);
    lv_obj_set_x(ui_Button17, 285);
    lv_obj_set_y(ui_Button17, -141);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0xF90101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button17, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button17, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Button17);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "stop");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_tactic40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button18 = lv_btn_create(ui_hostage);
    lv_obj_set_width(ui_Button18, 110);
    lv_obj_set_height(ui_Button18, 60);
    lv_obj_set_align(ui_Button18, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button18, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button18, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button18, &ui_img_mk_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button18, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);

}

void ui_hostage_screen_destroy(void)
{
    if(ui_hostage) lv_obj_del(ui_hostage);

    // NULL screen variables
    ui_hostage = NULL;
    ui_TextArea13 = NULL;
    ui_Button16 = NULL;
    ui_Label11 = NULL;
    ui_hostageTimer = NULL;
    ui_hostageResult = NULL;
    ui_Button17 = NULL;
    ui_Label12 = NULL;
    ui_Button18 = NULL;

}
