// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_menu = NULL;
lv_obj_t * ui_rankingbutton = NULL;
lv_obj_t * ui_settingsbutton = NULL;
lv_obj_t * ui_programsbutton = NULL;
// event funtions
void ui_event_rankingbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ranking, LV_SCR_LOAD_ANIM_FADE_ON, 127, 0, &ui_ranking_screen_init);
    }
}

void ui_event_settingsbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settings, LV_SCR_LOAD_ANIM_FADE_ON, 127, 0, &ui_settings_screen_init);
    }
}

void ui_event_programsbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PROGRAMS, LV_SCR_LOAD_ANIM_FADE_ON, 64, 0, &ui_PROGRAMS_screen_init);
    }
}

// build funtions

void ui_menu_screen_init(void)
{
    ui_menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menu, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_menu, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_menu, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rankingbutton = lv_imgbtn_create(ui_menu);
    lv_imgbtn_set_src(ui_rankingbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_ranking_png, NULL);
    lv_obj_set_width(ui_rankingbutton, 200);
    lv_obj_set_height(ui_rankingbutton, 320);
    lv_obj_set_x(ui_rankingbutton, 0);
    lv_obj_set_y(ui_rankingbutton, -20);
    lv_obj_set_align(ui_rankingbutton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_rankingbutton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_rankingbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_rankingbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_rankingbutton, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_rankingbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsbutton = lv_imgbtn_create(ui_menu);
    lv_imgbtn_set_src(ui_settingsbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_widget_settings_png, NULL);
    lv_obj_set_width(ui_settingsbutton, 200);
    lv_obj_set_height(ui_settingsbutton, 320);
    lv_obj_set_x(ui_settingsbutton, 250);
    lv_obj_set_y(ui_settingsbutton, -20);
    lv_obj_set_align(ui_settingsbutton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_settingsbutton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_settingsbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_settingsbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_settingsbutton, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_settingsbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_programsbutton = lv_imgbtn_create(ui_menu);
    lv_imgbtn_set_src(ui_programsbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_widget_programs_png, NULL);
    lv_obj_set_width(ui_programsbutton, 200);
    lv_obj_set_height(ui_programsbutton, 320);
    lv_obj_set_x(ui_programsbutton, -250);
    lv_obj_set_y(ui_programsbutton, -20);
    lv_obj_set_align(ui_programsbutton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_programsbutton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_programsbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_programsbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_programsbutton, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_programsbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_rankingbutton, ui_event_rankingbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsbutton, ui_event_settingsbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_programsbutton, ui_event_programsbutton, LV_EVENT_ALL, NULL);

}

void ui_menu_screen_destroy(void)
{
    if(ui_menu) lv_obj_del(ui_menu);

    // NULL screen variables
    ui_menu = NULL;
    ui_rankingbutton = NULL;
    ui_settingsbutton = NULL;
    ui_programsbutton = NULL;

}
