// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_PROGRAMS = NULL;
lv_obj_t * ui_trainingbutton = NULL;
lv_obj_t * ui_coverfirebutton = NULL;
lv_obj_t * ui_dynamicbutton = NULL;
lv_obj_t * ui_hostagebutton = NULL;
lv_obj_t * ui_heavyfirebutton = NULL;
lv_obj_t * ui_Button4 = NULL;
// event funtions
void ui_event_trainingbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_training, LV_SCR_LOAD_ANIM_FADE_ON, 64, 0, &ui_training_screen_init);
    }
}

void ui_event_coverfirebutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_coverfire, LV_SCR_LOAD_ANIM_FADE_ON, 64, 0, &ui_coverfire_screen_init);
    }
}

void ui_event_dynamicbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dynamic, LV_SCR_LOAD_ANIM_FADE_ON, 64, 0, &ui_dynamic_screen_init);
    }
}

void ui_event_hostagebutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_hostage, LV_SCR_LOAD_ANIM_FADE_ON, 64, 0, &ui_hostage_screen_init);
    }
}

void ui_event_heavyfirebutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_heavyfire, LV_SCR_LOAD_ANIM_FADE_ON, 64, 0, &ui_heavyfire_screen_init);
        hv_program_set(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_FADE_ON, 64, 0, &ui_menu_screen_init);
    }
}

// build funtions

void ui_PROGRAMS_screen_init(void)
{
    ui_PROGRAMS = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PROGRAMS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PROGRAMS, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PROGRAMS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PROGRAMS, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PROGRAMS, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_trainingbutton = lv_imgbtn_create(ui_PROGRAMS);
    lv_imgbtn_set_src(ui_trainingbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_trainig_png, NULL);
    lv_obj_set_width(ui_trainingbutton, 200);
    lv_obj_set_height(ui_trainingbutton, 200);
    lv_obj_set_x(ui_trainingbutton, 221);
    lv_obj_set_y(ui_trainingbutton, 106);
    lv_obj_set_align(ui_trainingbutton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_trainingbutton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_trainingbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_trainingbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_trainingbutton, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_trainingbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coverfirebutton = lv_imgbtn_create(ui_PROGRAMS);
    lv_imgbtn_set_src(ui_coverfirebutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cover_fire_png, NULL);
    lv_obj_set_width(ui_coverfirebutton, 200);
    lv_obj_set_height(ui_coverfirebutton, 200);
    lv_obj_set_x(ui_coverfirebutton, 221);
    lv_obj_set_y(ui_coverfirebutton, -116);
    lv_obj_set_align(ui_coverfirebutton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_coverfirebutton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_coverfirebutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_coverfirebutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_coverfirebutton, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_coverfirebutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dynamicbutton = lv_imgbtn_create(ui_PROGRAMS);
    lv_imgbtn_set_src(ui_dynamicbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_dynamic_png, NULL);
    lv_obj_set_width(ui_dynamicbutton, 200);
    lv_obj_set_height(ui_dynamicbutton, 200);
    lv_obj_set_x(ui_dynamicbutton, -4);
    lv_obj_set_y(ui_dynamicbutton, -7);
    lv_obj_set_align(ui_dynamicbutton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_dynamicbutton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dynamicbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dynamicbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dynamicbutton, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dynamicbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hostagebutton = lv_imgbtn_create(ui_PROGRAMS);
    lv_imgbtn_set_src(ui_hostagebutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_hostage_png, NULL);
    lv_obj_set_width(ui_hostagebutton, 200);
    lv_obj_set_height(ui_hostagebutton, 200);
    lv_obj_set_x(ui_hostagebutton, -227);
    lv_obj_set_y(ui_hostagebutton, 99);
    lv_obj_set_align(ui_hostagebutton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_hostagebutton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_hostagebutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_hostagebutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_hostagebutton, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_hostagebutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heavyfirebutton = lv_imgbtn_create(ui_PROGRAMS);
    lv_imgbtn_set_src(ui_heavyfirebutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_heavy_fire_png, NULL);
    lv_obj_set_width(ui_heavyfirebutton, 200);
    lv_obj_set_height(ui_heavyfirebutton, 200);
    lv_obj_set_x(ui_heavyfirebutton, -227);
    lv_obj_set_y(ui_heavyfirebutton, -117);
    lv_obj_set_align(ui_heavyfirebutton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_heavyfirebutton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_heavyfirebutton, &ui_img_dynamic_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_heavyfirebutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_heavyfirebutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_heavyfirebutton, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_heavyfirebutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_PROGRAMS);
    lv_obj_set_width(ui_Button4, 110);
    lv_obj_set_height(ui_Button4, 60);
    lv_obj_set_align(ui_Button4, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button4, &ui_img_mk_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button4, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_trainingbutton, ui_event_trainingbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_coverfirebutton, ui_event_coverfirebutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dynamicbutton, ui_event_dynamicbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hostagebutton, ui_event_hostagebutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_heavyfirebutton, ui_event_heavyfirebutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_PROGRAMS_screen_destroy(void)
{
    if(ui_PROGRAMS) lv_obj_del(ui_PROGRAMS);

    // NULL screen variables
    ui_PROGRAMS = NULL;
    ui_trainingbutton = NULL;
    ui_coverfirebutton = NULL;
    ui_dynamicbutton = NULL;
    ui_hostagebutton = NULL;
    ui_heavyfirebutton = NULL;
    ui_Button4 = NULL;

}
