// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_start_screen = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_FADE_ON, 64, 0, &ui_menu_screen_init);
    }
}

// build funtions

void ui_start_screen_screen_init(void)
{
    ui_start_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_start_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_start_screen, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_start_screen, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_start_screen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imgbtn_create(ui_start_screen);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_start_screen2_png, NULL);
    lv_obj_set_width(ui_ImgButton1, 800);
    lv_obj_set_height(ui_ImgButton1, 460);
    lv_obj_set_x(ui_ImgButton1, -1);
    lv_obj_set_y(ui_ImgButton1, -13);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_Label5 = lv_label_create(ui_start_screen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label5, "version 1.0.0");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);

}

void ui_start_screen_screen_destroy(void)
{
    if(ui_start_screen) lv_obj_del(ui_start_screen);

    // NULL screen variables
    ui_start_screen = NULL;
    ui_ImgButton1 = NULL;
    ui_Label5 = NULL;

}
