// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_training = NULL;
lv_obj_t * ui_TextArea10 = NULL;
lv_obj_t * ui_Button13 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_trainingTimer = NULL;
lv_obj_t * ui_trainingResult = NULL;
lv_obj_t * ui_Button14 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Button15 = NULL;
// event funtions
void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        training_start_clbk(e);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        training_stop_clbk(e);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PROGRAMS, LV_SCR_LOAD_ANIM_FADE_ON, 64, 0, &ui_PROGRAMS_screen_init);
    }
}

// build funtions

void ui_training_screen_init(void)
{
    ui_training = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_training, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_training, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_training, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_training, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_training, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea10 = lv_textarea_create(ui_training);
    lv_obj_set_width(ui_TextArea10, 350);
    lv_obj_set_height(ui_TextArea10, 347);
    lv_obj_set_x(ui_TextArea10, -195);
    lv_obj_set_y(ui_TextArea10, -22);
    lv_obj_set_align(ui_TextArea10, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea10,
                         "Zaczynamy od jednego aktywnego celu. \nTrafienie aktywuje kolejny cel oraz zostawia trafiony.\n5 cykli.\n\nKolor aktywnego celu:\nczerwony\nKolor trafionego celu:\nzielony\n\nCzas: 5 cykli.\nWynik: Czas");
    lv_textarea_set_placeholder_text(ui_TextArea10, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextArea10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TextArea10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextArea10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea10, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea10, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TextArea10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TextArea10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TextArea10, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TextArea10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_btn_create(ui_training);
    lv_obj_set_width(ui_Button13, 150);
    lv_obj_set_height(ui_Button13, 100);
    lv_obj_set_x(ui_Button13, 101);
    lv_obj_set_y(ui_Button13, -142);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0x11B532), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button13, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button13, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "start");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_tactic40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_trainingTimer = lv_textarea_create(ui_training);
    lv_obj_set_width(ui_trainingTimer, 150);
    lv_obj_set_height(ui_trainingTimer, 130);
    lv_obj_set_x(ui_trainingTimer, 99);
    lv_obj_set_y(ui_trainingTimer, 42);
    lv_obj_set_align(ui_trainingTimer, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_trainingTimer, "TIMER & STOPER");
    lv_textarea_set_placeholder_text(ui_trainingTimer, "Placeholder...");
    lv_obj_set_style_text_font(ui_trainingTimer, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_trainingResult = lv_textarea_create(ui_training);
    lv_obj_set_width(ui_trainingResult, 150);
    lv_obj_set_height(ui_trainingResult, 128);
    lv_obj_set_x(ui_trainingResult, 288);
    lv_obj_set_y(ui_trainingResult, 43);
    lv_obj_set_align(ui_trainingResult, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_trainingResult, "TRAFIENIA");
    lv_textarea_set_placeholder_text(ui_trainingResult, "Placeholder...");
    lv_obj_set_style_text_font(ui_trainingResult, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_trainingResult, &lv_font_montserrat_16, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Button14 = lv_btn_create(ui_training);
    lv_obj_set_width(ui_Button14, 150);
    lv_obj_set_height(ui_Button14, 100);
    lv_obj_set_x(ui_Button14, 285);
    lv_obj_set_y(ui_Button14, -141);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0xF90101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button14, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button14, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "stop");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_tactic40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_btn_create(ui_training);
    lv_obj_set_width(ui_Button15, 110);
    lv_obj_set_height(ui_Button15, 60);
    lv_obj_set_align(ui_Button15, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button15, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button15, &ui_img_mk_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button15, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);

}

void ui_training_screen_destroy(void)
{
    if(ui_training) lv_obj_del(ui_training);

    // NULL screen variables
    ui_training = NULL;
    ui_TextArea10 = NULL;
    ui_Button13 = NULL;
    ui_Label9 = NULL;
    ui_trainingTimer = NULL;
    ui_trainingResult = NULL;
    ui_Button14 = NULL;
    ui_Label10 = NULL;
    ui_Button15 = NULL;

}
